acknowledgements
go101korea/go101 pull request #57
Opened 2023-01-26 09:44 UTC by kjy8901

Signed-off-by: kjy8901 <kjy8901@gluesys.com>

2023-01-27 07:06 UTC, potatogim requested changes

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Go 101 eBook을 제작을 위해주신
eBook보다 전자책이라고 표현하면 더 좋을 것 같은데 어떤가요? ㅎㅎ

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +<a href="https://prismjs.com/">prism syntax highlighting</a> JavaSript 패키지
- JavaSript -> JavaScript

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Go 커뮤니티에는 친절하고 창의적인 gophers가 너무 많아서 누군가를 놓쳤을 수도 있습니다.
- gophers -> 고퍼들(Gophers)
- 약간의 의역이 들어가면 더 자연스럽게 느껴질 것 같네요 ㅎㅎ

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +또한 Go101책에 직접적이던 간접적이던, 의도적이던 비의도적이던 영향을 준 모든 gopher들에게 감사를 표하고 싶습니다.
- Go101책에 -> Go 101 책에
- gopher -> 고퍼(Gopher)

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Reddit에 작성한 Go 기사 중 하나에서 실수를 지적해 준 Martin Möhrmann에게 감사드립니다.
사람을 지칭할 때에는 ~씨와 같은 형태가 좋을 것 같은데 어때요?

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +또한 Go 프로젝트 이슈트래커에서 많은 것을 배울 수 있었습니다.
- 이슈트래커 -> 이슈 트래커

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 스레드에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
- 스레드 -> 글타래

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor에게는 특별히 감사를 전하고 싶습니다.
- Taylor에게는 -> Taylor씨에게는

2023-01-27 07:06 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Ian은 go-nuts 그룹과 Go 프로젝트 이슈 트래커에 제가 올린 셀 수 없는 지루한 질문에 친절하게 답해주셨습니다.
전체적으로 어떤 분위기로 글을 풀어갈 것인지 고민이 필요해보이네요!

요건 이슈로 논의해보죠~!

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Go 101 eBook을 제작을 위해주신
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +<a href="https://prismjs.com/">prism syntax highlighting</a> JavaSript 패키지
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Go 커뮤니티에는 친절하고 창의적인 gophers가 너무 많아서 누군가를 놓쳤을 수도 있습니다.
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +또한 Go101책에 직접적이던 간접적이던, 의도적이던 비의도적이던 영향을 준 모든 gopher들에게 감사를 표하고 싶습니다.
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +또한 Go 프로젝트 이슈트래커에서 많은 것을 배울 수 있었습니다.
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 스레드에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
수정했습니다~

2023-01-27 07:56 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor에게는 특별히 감사를 전하고 싶습니다.
수정했습니다~

2023-01-27 08:02 UTC, potatogim submitted a review, later dismissed
:+1

2023-01-27 08:06 UTC, AngeliKaroS commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
밑에 이름들 중에 etc가 있네용 얘도 바꿔주는게 일단 맞지 않을까 싶습니다

2023-01-27 08:09 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
수정했습니다~

2023-01-27 08:14 UTC, kjy8901 commented
resolve #2

2023-01-27 08:16 UTC, AngeliKaroS commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
다른 곳도 말씀 드렸어야 했는데 죄송합니다

이 보다 더 밑에있는 목록들에도 etc가 몇개 더 있습니다 ㅎ...

수정하셨다면.. 비슷하게 바꾸는게 좋지 않을까 싶습니다

2023-01-27 08:16 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
앗 그러네영....쏴리....

2023-01-27 08:18 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
수정완료 했습니당

2023-01-31 06:54 UTC, hspark0582 requested changes

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor 씨에게는 특별히 감사를 전하고 싶습니다.
'에게'를 '께'로 바꾸고 뒤에 '는'은 딱히 필요 없어 보입니다.

그리고 사람 이름 뒤에 '씨'를 쓰기로 한 건 알지만 감사의 말에서는 '님'이 나아보이는데 다들 어떻게 생각하시나요

```suggestion
Ian Lance Taylor 님께 특별히 감사를 전하고 싶습니다.
```

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +Ian 씨는 go-nuts 그룹과 Go 프로젝트 이슈 트래커에 제가 올린 수많은 답답한 질문에 친절하게 답해주셨습니다.
'boring'을 '답답한'으로 옮기기는 좀 어려울 것 같고 '시시콜콜한' 어떠십니까

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
**<의견 받습니다>**

영어에서는 콜론(:), 세미콜론(;), 대시(&mdash;) 등의 부호로 문장들을 이을 수 있는데 한국어 문법에서는 이러한 사용을 규정하지 않는 것으로 알고 있습니다.
다른 글 읽으면서 마주치면 바로 "아 이거 번역한 글이네"라는 느낌이 드는 표현인데 여러분들은 어떻게 생각하시나요

(그렇다고 이미 번역하신 걸 고쳐야 할 정도는 아닌 것 같슴다)

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +Reddit에 작성한 Go 기사 중 하나에서 실수를 지적해 준 Martin Möhrmann 씨에게 감사드립니다.
```suggestion
Reddit에 작성한 Go 기사 중 하나에서 실수를 지적해 준 Martin Möhrmann 씨께 감사드립니다.
```

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +Go 101 전자책 제작을 위해주신
```suggestion
Go 101 전자책 제작을 맡아주신
```

오타인가요? 그냥 제가 모르는 표현일수도 있지만...

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +작성자에게 감사드립니다.
```suggestion
작성자께 감사드립니다.
```

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +전자책 제안에 좋은 제안을 해주신 Adam Chalkley 씨에게 감사드립니다.
```suggestion
전자책 제작을 제안해주신 Adam Chalkley 씨께 감사드립니다.
```

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +다음 분들을 포함하여 Go 101 책을 개선해준 모든 Go 101 기여자분들에게 감사드립니다:
```suggestion
다음 분들을 포함하여 Go 101 책을 개선해준 모든 Go 101 기여자분들께 감사드립니다:
```

2023-01-31 06:54 UTC, hspark0582 commented on pages/fundamentals/acknowledgements.html
> +Go 프로젝트 이슈 트래커에서 활동하고 있는 다음 사람들에게 감사드립니다.:
```suggestion
Go 프로젝트 이슈 트래커에서 활동하고 계시는 다음 분들께 감사드립니다.:
```

2023-01-31 07:28 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor 씨에게는 특별히 감사를 전하고 싶습니다.
개인적으로는 그냥 씨로 해도 무관할 것 같네요 ㅎㅎ

2023-01-31 07:30 UTC, potatogim commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor 씨에게는 특별히 감사를 전하고 싶습니다.
`께`는 보통 님과 같은 존칭 뒤에 붙이는 존대 표현 조사라 씨를 사용하다면 `에게` 정도로 정리해도 되지 않을까 싶네요~!

2023-01-31 07:37 UTC, AngeliKaroS commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
확실히 일반적으로 사용하지는 않으니 좀 위화감이 없지 않아 있긴 한 것 같습니당

2023-01-31 09:10 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Ian Lance Taylor 씨에게는 특별히 감사를 전하고 싶습니다.
여러 의견을 조합하여...
일단 `~씨`를 기본으로 하였습니다
`께`의 경우에는 지현씨의 의견을 생각하여 `~분들께`와 같이 앞에 높이는 경우에 한하여 수정하였습니다

2023-01-31 09:10 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Ian 씨는 go-nuts 그룹과 Go 프로젝트 이슈 트래커에 제가 올린 수많은 답답한 질문에 친절하게 답해주셨습니다.
수정했습니다

2023-01-31 09:10 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +go-nuts 및 go-dev 그룹의 질문 글 타래에 참여해 주신 다음 분들에게 감사의 인사를 전하고 싶습니다:
안그래도 보기 거슬렸었는데 의견을 받아서 다 빼버렸슴다!

2023-01-31 09:11 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +Go 101 전자책 제작을 위해주신
요기도 수정하였슴다

2023-01-31 09:11 UTC, kjy8901 commented on pages/fundamentals/acknowledgements.html
> +기타 다른 모든 분들.
수정했슴다

2023-02-01 05:29 UTC, potatogim approved these changes
고생 많았어요~!

2023-02-01 05:47 UTC, AngeliKaroS approved these changes

2023-02-01 05:49 UTC, hspark0582 submitted a review, later dismissed

2023-02-01 05:53 UTC, potatogim commented
커밋 서명이 안되어있어서 병합이 불가능하네요~!

2023-02-01 06:12 UTC, AngeliKaroS approved these changes

2023-02-01 06:26 UTC, hspark0582 approved these changes

2023-02-05 11:23 UTC, potatogim approved these changes

2023-02-05 11:28 UTC, merged