Draft: Line break rules
go101korea/go101 pull request #61
Opened 2023-01-30 08:28 UTC by hspark0582

수정중: PR 준비되면 멘션 드리겠습니다.

2023-01-31 07:48 UTC, hspark0582 reviewed
의견 필요한 부분들에 댓글 달아두었습니다. 물론 댓글 없는 곳도 리뷰 잘 부탁드리겠습니다. 꾸벅

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +    // 아래 두 줄 모두 컴파일에 실패합니다.
Known issue: 탭/스페이스 다음 커밋에서 고치겠습니다

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +또한 선택자(selector) <code>.</code> 앞에서 줄을 바꿀 수 없는 것도
selector 번역 맞는지 봐 주십셔

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +composite literals, function argument lists, function parameter lists, 그리고 function result lists와 같은
Go에서 얘네들이 정확히 뭘 의미하는지 몰라서 그대로 놔뒀습니다. 도와주십쇼

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +위 예시에 나와 있는 세 개의 제어 흐름(control flow) 블록은 모두 유효합니다.
위키백과에서 control flow를 제어 흐름이라고 번역하던데 이걸 제가 들어본 적이 없어서 다들 쓰는 표현인건지 원문을 남겨놔야 할지 (그냥 알파벳으로 "control flow"/한글로 "컨트롤 플로우"/"제어 흐름(control flow)"/"제어 흐름"만) 의견 주시면 좋겠습니다.

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +실무에서 우리는 "명시적인 코드 블록을 시작하는 중괄호(<code>{</code>) 전에 줄 바꿈을 하지 않는다"라는
"code block" 번역 포기하고 코드 블록이라고 적었습니다. 더 나은 표현 있으시면 알려주세요.

2023-01-31 07:48 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +문(statement)으로만 사용이 가능합니다.
expression, statement: 검색해보니 식과 문으로 번역하는 곳이 많은 것 같던데 어떻게 생각하시나요?
statement는 밑에서도 잔뜩 쓰이는데 '문' 한 글자 번역어를 자연스럽게 쓸 수가 없어서 그냥 statement로 내버려둔 상태입니다.
의견 부탁드립니다.

2023-01-31 07:54 UTC, AngeliKaroS commented on pages/fundamentals/line-break-rules.html
> +위 예시에 나와 있는 세 개의 제어 흐름(control flow) 블록은 모두 유효합니다.
제어 흐름으로 번역 해두고 원어 적어두는게 좋지 않을까 싶습니다

2023-01-31 07:56 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +또한 선택자(selector) <code>.</code> 앞에서 줄을 바꿀 수 없는 것도
기존에 Go 명세를 번역할 때에도 선택자라는 용어를 사용했던 걸로 기억되네요!
무난한 것 같습니다~!

2023-01-31 08:02 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +composite literals, function argument lists, function parameter lists, 그리고 function result lists와 같은
- Composite Literal은 합성 리터럴로 번역을 했었고, 구조체 등의 초기화에서 멤버를 목록으로 나열하여 표기하는 형태를 나타냅니다~!
- `함수의 전달인자 목록, 매개변수 목록과 반환값 목록` 정도로 정리할 수 있을 듯~!

2023-01-31 08:04 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +문(statement)으로만 사용이 가능합니다.
- expression의 경우 상황에 따라 조금씩 다를 수는 있을 것 같은데 주로 `표현식`으로 번역을 했었네요!
- statement의 경우에는 `구문`으로 주로 번역을 했었어요~!

2023-01-31 08:10 UTC, potatogim requested changes

2023-01-31 08:10 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +예를 들어, 다음 <code>for</code> 루프 코드는 컴파일에 실패합니다.
루프는 주로 반복문으로 번역을 했던 것 같네요~!

2023-01-31 08:10 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +	입력이 언어요소로 해석될 때, 줄의 마지막 언어요소가 다음과 같은 경우,
- 기존에는 token을 그냥 토큰으로 번역했던 것 같네요~!

2023-01-31 08:10 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +비슷한 항목들을 여러 개 포함하는 몇몇 구문들은 그 항목들을 구분하기 위해 반점을 사용합니다.
- `반점` -> `쉼표(,)` 요런 정도로?

2023-01-31 08:11 UTC, kjy8901 commented on pages/fundamentals/line-break-rules.html
> +실무에서 우리는 "명시적인 코드 블록을 시작하는 중괄호(<code>{</code>) 전에 줄 바꿈을 하지 않는다"라는
다른데서도 그냥 코드블록으로 사용하는거 같네용

2023-01-31 08:19 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +	입력이 언어요소로 해석될 때, 줄의 마지막 언어요소가 다음과 같은 경우,
여기는 https://github.com/golangkorea/golang-spec/blob/master/ko/Lexical%20elements/semicolons.md 복붙했습니다.

2023-01-31 08:19 UTC, lhjnano commented on pages/fundamentals/line-break-rules.html
> +대부분의 Go 문법에서 공식적으로 세미콜론 ";" 을 종결자로 사용한다.
여기서부터 109 라인까지 어체 분위기가 갑자기 바뀐거 같아요

2023-01-31 08:20 UTC, kjy8901 commented on pages/fundamentals/line-break-rules.html
> +두 번째 규칙은 여러 항목을 선언한 뒤 오는 닫는 괄호 <code>)</code> 앞과 코드 블록이나 형 (struct나
```suggestion
두 번째 규칙은 여러 항목을 선언한 뒤 오는 닫는 괄호 <code>)</code> 앞과 코드 블록이나 유형 (struct나
```
이 더 낫지 않나 의견드립니당

2023-01-31 08:21 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +대부분의 Go 문법에서 공식적으로 세미콜론 ";" 을 종결자로 사용한다.
https://github.com/golangkorea/golang-spec/blob/master/ko/Lexical%20elements/semicolons.md

이미 번역된 명세 복붙이라 그렇습니다. 제가 직접 번역했더라도 명세를 인용한 부분이니 이런 식으로 했을 것 같습니다.

2023-01-31 08:27 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +두 번째 규칙은 여러 항목을 선언한 뒤 오는 닫는 괄호 <code>)</code> 앞과 코드 블록이나 형 (struct나
아 이것도 있었네요 그냥 타입이라고 쓸까 하다 형으로 옮겼는데요.
타입을 유형으로 번역한 건 본 적은 없는 것 같은데 다들 어떻게 생각하시나요?

2023-01-31 08:32 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +두 번째 규칙은 여러 항목을 선언한 뒤 오는 닫는 괄호 <code>)</code> 앞과 코드 블록이나 형 (struct나
문맥에 따라 다르겠지만 이 경우에는 `자료형` 정도면 좋지 않을까 싶네요~!

2023-01-31 08:35 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +	입력이 언어요소로 해석될 때, 줄의 마지막 언어요소가 다음과 같은 경우,
해당 번역이 용어집 참고가 안되었거나 이후에 용어집에 추가된 것 같네요~

https://github.com/golangkorea/golang-spec/blob/2315994e5fdf2d476b48d09692740e49088c244b/ko/GLOSSARY.md#token

2023-01-31 08:36 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +비슷한 항목들을 여러 개 포함하는 몇몇 구문들은 그 항목들을 구분하기 위해 반점을 사용합니다.
반점 전부 쉼표로 바꾸는게 나을까요?

2023-01-31 08:43 UTC, hspark0582 commented on pages/fundamentals/line-break-rules.html
> +	입력이 언어요소로 해석될 때, 줄의 마지막 언어요소가 다음과 같은 경우,
아 이런 glossary가 있었네요... 왜 못 봤을까요...
여기에 따르면 type은 그냥 타입이네요. 용어 번역을 명세에 맞추는 게 좋을까요?

2023-01-31 09:10 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +	입력이 언어요소로 해석될 때, 줄의 마지막 언어요소가 다음과 같은 경우,
음~ 100% 따라갈 필요는 없을 것 같고 우리도 우리 나름의 용어집을 하나 정리하는 걸로 하죠~! ㅎㅎ

2023-01-31 09:10 UTC, potatogim commented on pages/fundamentals/line-break-rules.html
> +비슷한 항목들을 여러 개 포함하는 몇몇 구문들은 그 항목들을 구분하기 위해 반점을 사용합니다.
가능하면 통일시키는게 좋을 듯~!

2023-02-01 05:15 UTC, AngeliKaroS submitted a review, later dismissed

2023-02-01 05:28 UTC, potatogim approved these changes
고생 많았어요~!

2023-02-01 05:53 UTC, potatogim commented
여기도 혹시 커밋 서명 안되어있으면 서명 부탁할게요~!

2023-02-06 09:06 UTC, potatogim submitted a review, later dismissed

2023-02-06 10:19 UTC, AngeliKaroS approved these changes

2023-02-07 05:15 UTC, kjy8901 submitted a review, later dismissed

2023-02-07 05:18 UTC, potatogim approved these changes

2023-02-07 05:21 UTC, AngeliKaroS approved these changes

2023-02-07 05:22 UTC, kjy8901 approved these changes

2023-02-07 05:27 UTC, lhjnano approved these changes

2023-02-07 06:10 UTC, merged